### ISSUE TITLE
Synology

### ISSUE THREAD

**Issue by noureddin212** [ycahome/pp-manager#11]
![max](https://user-images.githubusercontent.com/33298815/48403490-42cc5780-e72e-11e8-9f5a-4f9b0be472b6.jpg)

I was not able to install a plugin (MaxCube) this si the first plugin .
I copy paste the command LANG=en_US /usr/bin/git  clone -b ...
the command did not work 
I had to use sudo to launch this line

**Comment by ycahome** [comment]
Hello,

thanks for your report. Unfortunately i don't have Domoticz on my Synology.
So, you always install plugins with sudo?

**Comment by noureddin212** [comment]
Yes indeed only with sudo

**Comment by ycahome** [comment]
and? system always requests for your user password upon use of sudo?

**Comment by noureddin212** [comment]
every day I have also an error @ 12h :


2018-11-13 12:00:04.408 Error: (PPM) 'onHeartbeat' failed 'NameError':'name
'pluginKey' is not defined'.
2018-11-13 12:00:04.408 Error: (PPM) ----> Line 744 in
/usr/local/domoticz/var/plugins/PP-MANAGER/plugin.py, function onHeartbeat
2018-11-13 12:00:04.408 Error: (PPM) ----> Line 418 in
/usr/local/domoticz/var/plugins/PP-MANAGER/plugin.py, function onHeartbeat

**Comment by ycahome** [comment]
pluginKey variable taking value from "Plugin to install".

Can you tell me which plugin you have selected?

**Comment by noureddin212** [comment]
Eq3max

**Comment by ycahome** [comment]
In fact this is the only plugin with an exclamation mark in its display name. Am checking it.

**Comment by ycahome** [comment]
fixed in v.1.5.14

**Comment by noureddin212** [comment]
sorry it is not ok
I still have the issue I tryed to install ikea trafdi
Same error

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
